# MySQL PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    app: mysql
spec:
  storageClassName: mysql-storage
  capacity:
    storage: 120Mi  
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"



