apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: db-backup-lease
  namespace: db-backup
spec:
  holderIdentity: ""
  leaseDurationSeconds: 3600 
  acquireTime: null
  renewTime: null
  leaderTransitions: 0
